name: Trigger CircleCI on Main Merge

on:
  pull_request:
    branches:
      - main
    types: [closed] # PRがマージされたときに実行

jobs:
  trigger_circleci: # ← このジョブ定義があるか確認
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: actions/curl@v2
        env:
          CIRCLECI_API_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "${{ env.CIRCLECI_API_TOKEN }}:" \
            -d '{"branch": "main"}' \
            "https://circleci.com/api/v2/project/gh/${{ github.repository_owner }}/${{ github.event.repository.name }}/pipeline"