name: Deploy with Manual Approval (GitHub Actions Only)

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Simulate Deployment
        run: echo "Manually approved. Simulating deployment to production..."
        # 実際のデプロイ処理 (まだサーバーがないので echo で代用)